name: main_workflows
run-name: ${{ github.actor }} is modify the repos
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Installe java 8 sur l'agent
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    # Compile notre application
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
        
    # Installe la commande docker sur l'agent
    - name: Install Docker
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
        
    # Build l'image Docker
    - name: Docker build
      run: |
        docker build .